
export enum DataTypeIds {
   CertificateAuthorityType = 'i=1164',
   BaseTicketType = 'i=1165',
   DeviceIdentityTicketType = 'i=1166',
   CompositeIdentityTicketType = 'i=1167',
   TicketListType = 'i=1168',
   ManagerDescription = 'i=1495'
}

export enum MethodIds {
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Open = 'i=17',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Close = 'i=20',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Read = 'i=22',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Write = 'i=25',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_GetPosition = 'i=27',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_SetPosition = 'i=30',
   DeviceRegistrarAdminType_RegisterTickets = 'i=1176',
   DeviceRegistrarAdminType_UnregisterTickets = 'i=1179',
   DeviceRegistrarAdminType_TicketAuthorities_Open = 'i=1190',
   DeviceRegistrarAdminType_TicketAuthorities_Close = 'i=1193',
   DeviceRegistrarAdminType_TicketAuthorities_Read = 'i=1195',
   DeviceRegistrarAdminType_TicketAuthorities_Write = 'i=1198',
   DeviceRegistrarAdminType_TicketAuthorities_GetPosition = 'i=1200',
   DeviceRegistrarAdminType_TicketAuthorities_SetPosition = 'i=1203',
   DeviceRegistrarAdminType_TicketAuthorities_OpenWithMasks = 'i=1208',
   DeviceRegistrarAdminType_TicketAuthorities_CloseAndUpdate = 'i=1211',
   DeviceRegistrarAdminType_TicketAuthorities_AddCertificate = 'i=1214',
   DeviceRegistrarAdminType_TicketAuthorities_RemoveCertificate = 'i=1216',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_Open = 'i=1226',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_Close = 'i=1229',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_Read = 'i=1231',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_Write = 'i=1234',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_GetPosition = 'i=1236',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_SetPosition = 'i=1239',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_OpenWithMasks = 'i=1244',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_CloseAndUpdate = 'i=1247',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_AddCertificate = 'i=1250',
   DeviceRegistrarAdminType_DeviceIdentityAuthorities_RemoveCertificate = 'i=1252',
   DeviceRegistrarType_ProvideIdentities = 'i=1260',
   DeviceRegistrarType_UpdateSoftwareStatus = 'i=1503',
   DeviceRegistrarType_RegisterDeviceEndpoint = 'i=1263',
   DeviceRegistrarType_GetManagers = 'i=1505',
   DeviceRegistrarType_RegisterManagedApplication = 'i=1507',
   DeviceRegistrarType_Administration_RegisterTickets = 'i=1266',
   DeviceRegistrarType_Administration_UnregisterTickets = 'i=1269',
   DeviceRegistrarType_Administration_TicketAuthorities_Open = 'i=1280',
   DeviceRegistrarType_Administration_TicketAuthorities_Close = 'i=1283',
   DeviceRegistrarType_Administration_TicketAuthorities_Read = 'i=1285',
   DeviceRegistrarType_Administration_TicketAuthorities_Write = 'i=1288',
   DeviceRegistrarType_Administration_TicketAuthorities_GetPosition = 'i=1290',
   DeviceRegistrarType_Administration_TicketAuthorities_SetPosition = 'i=1293',
   DeviceRegistrarType_Administration_TicketAuthorities_OpenWithMasks = 'i=1298',
   DeviceRegistrarType_Administration_TicketAuthorities_CloseAndUpdate = 'i=1301',
   DeviceRegistrarType_Administration_TicketAuthorities_AddCertificate = 'i=1304',
   DeviceRegistrarType_Administration_TicketAuthorities_RemoveCertificate = 'i=1306',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_Open = 'i=1316',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_Close = 'i=1319',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_Read = 'i=1321',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_Write = 'i=1324',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_GetPosition = 'i=1326',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_SetPosition = 'i=1329',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_OpenWithMasks = 'i=1334',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_CloseAndUpdate = 'i=1337',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_AddCertificate = 'i=1340',
   DeviceRegistrarType_Administration_DeviceIdentityAuthorities_RemoveCertificate = 'i=1342',
   DeviceRegistrar_ProvideIdentities = 'i=1345',
   DeviceRegistrar_UpdateSoftwareStatus = 'i=1510',
   DeviceRegistrar_RegisterDeviceEndpoint = 'i=1348',
   DeviceRegistrar_GetManagers = 'i=1512',
   DeviceRegistrar_RegisterManagedApplication = 'i=1514',
   DeviceRegistrar_Administration_RegisterTickets = 'i=1351',
   DeviceRegistrar_Administration_UnregisterTickets = 'i=1354',
   DeviceRegistrar_Administration_TicketAuthorities_Open = 'i=1365',
   DeviceRegistrar_Administration_TicketAuthorities_Close = 'i=1368',
   DeviceRegistrar_Administration_TicketAuthorities_Read = 'i=1370',
   DeviceRegistrar_Administration_TicketAuthorities_Write = 'i=1373',
   DeviceRegistrar_Administration_TicketAuthorities_GetPosition = 'i=1375',
   DeviceRegistrar_Administration_TicketAuthorities_SetPosition = 'i=1378',
   DeviceRegistrar_Administration_TicketAuthorities_OpenWithMasks = 'i=1383',
   DeviceRegistrar_Administration_TicketAuthorities_CloseAndUpdate = 'i=1386',
   DeviceRegistrar_Administration_TicketAuthorities_AddCertificate = 'i=1389',
   DeviceRegistrar_Administration_TicketAuthorities_RemoveCertificate = 'i=1391',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Open = 'i=1401',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Close = 'i=1404',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Read = 'i=1406',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Write = 'i=1409',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_GetPosition = 'i=1411',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_SetPosition = 'i=1414',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_OpenWithMasks = 'i=1419',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_CloseAndUpdate = 'i=1422',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_AddCertificate = 'i=1425',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_RemoveCertificate = 'i=1427'
}

export enum ObjectIds {
   OPCUAOnboardingNamespaceMetadata = 'i=1',
   DeviceRegistrar = 'i=1344',
   DeviceRegistrar_Administration = 'i=1350',
   DeviceRegistrar_Administration_TicketAuthorities = 'i=1357',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities = 'i=1393',
   ManagerDescription_Encoding_DefaultBinary = 'i=4206',
   ManagerDescription_Encoding_DefaultXml = 'i=4214',
   ManagerDescription_Encoding_DefaultJson = 'i=4222'
}

export enum ObjectTypeIds {
   DeviceRegistrarAdminType = 'i=1175',
   DeviceRegistrarType = 'i=1259',
   DeviceRegistrationAuditEventType = 'i=1517',
   DeviceIdentityAcceptedAuditEventType = 'i=1533',
   DeviceSoftwareUpdatedAuditEventType = 'i=1552'
}

export enum VariableIds {
   OPCUAOnboardingNamespaceMetadata_NamespaceUri = 'i=2',
   OPCUAOnboardingNamespaceMetadata_NamespaceVersion = 'i=3',
   OPCUAOnboardingNamespaceMetadata_NamespacePublicationDate = 'i=4',
   OPCUAOnboardingNamespaceMetadata_IsNamespaceSubset = 'i=5',
   OPCUAOnboardingNamespaceMetadata_StaticNodeIdTypes = 'i=6',
   OPCUAOnboardingNamespaceMetadata_StaticNumericNodeIdRange = 'i=7',
   OPCUAOnboardingNamespaceMetadata_StaticStringNodeIdPattern = 'i=8',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Size = 'i=10',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Writable = 'i=11',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_UserWritable = 'i=12',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_OpenCount = 'i=13',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Open_InputArguments = 'i=18',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Open_OutputArguments = 'i=19',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Close_InputArguments = 'i=21',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Read_InputArguments = 'i=23',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Read_OutputArguments = 'i=24',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_Write_InputArguments = 'i=26',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_GetPosition_InputArguments = 'i=28',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_GetPosition_OutputArguments = 'i=29',
   OPCUAOnboardingNamespaceMetadata_NamespaceFile_SetPosition_InputArguments = 'i=31',
   OPCUAOnboardingNamespaceMetadata_DefaultRolePermissions = 'i=33',
   OPCUAOnboardingNamespaceMetadata_DefaultUserRolePermissions = 'i=34',
   OPCUAOnboardingNamespaceMetadata_DefaultAccessRestrictions = 'i=35',
   DeviceRegistrar_ProvideIdentities_InputArguments = 'i=1346',
   DeviceRegistrar_ProvideIdentities_OutputArguments = 'i=1347',
   DeviceRegistrar_UpdateSoftwareStatus_InputArguments = 'i=1511',
   DeviceRegistrar_RegisterDeviceEndpoint_InputArguments = 'i=1349',
   DeviceRegistrar_GetManagers_OutputArguments = 'i=1513',
   DeviceRegistrar_RegisterManagedApplication_InputArguments = 'i=1515',
   DeviceRegistrar_RegisterManagedApplication_OutputArguments = 'i=1516',
   DeviceRegistrar_Administration_RegisterTickets_InputArguments = 'i=1352',
   DeviceRegistrar_Administration_RegisterTickets_OutputArguments = 'i=1353',
   DeviceRegistrar_Administration_UnregisterTickets_InputArguments = 'i=1355',
   DeviceRegistrar_Administration_UnregisterTickets_OutputArguments = 'i=1356',
   DeviceRegistrar_Administration_TicketAuthorities_Size = 'i=1358',
   DeviceRegistrar_Administration_TicketAuthorities_Writable = 'i=1359',
   DeviceRegistrar_Administration_TicketAuthorities_UserWritable = 'i=1360',
   DeviceRegistrar_Administration_TicketAuthorities_OpenCount = 'i=1361',
   DeviceRegistrar_Administration_TicketAuthorities_Open_InputArguments = 'i=1366',
   DeviceRegistrar_Administration_TicketAuthorities_Open_OutputArguments = 'i=1367',
   DeviceRegistrar_Administration_TicketAuthorities_Close_InputArguments = 'i=1369',
   DeviceRegistrar_Administration_TicketAuthorities_Read_InputArguments = 'i=1371',
   DeviceRegistrar_Administration_TicketAuthorities_Read_OutputArguments = 'i=1372',
   DeviceRegistrar_Administration_TicketAuthorities_Write_InputArguments = 'i=1374',
   DeviceRegistrar_Administration_TicketAuthorities_GetPosition_InputArguments = 'i=1376',
   DeviceRegistrar_Administration_TicketAuthorities_GetPosition_OutputArguments = 'i=1377',
   DeviceRegistrar_Administration_TicketAuthorities_SetPosition_InputArguments = 'i=1379',
   DeviceRegistrar_Administration_TicketAuthorities_LastUpdateTime = 'i=1380',
   DeviceRegistrar_Administration_TicketAuthorities_OpenWithMasks_InputArguments = 'i=1384',
   DeviceRegistrar_Administration_TicketAuthorities_OpenWithMasks_OutputArguments = 'i=1385',
   DeviceRegistrar_Administration_TicketAuthorities_CloseAndUpdate_InputArguments = 'i=1387',
   DeviceRegistrar_Administration_TicketAuthorities_CloseAndUpdate_OutputArguments = 'i=1388',
   DeviceRegistrar_Administration_TicketAuthorities_AddCertificate_InputArguments = 'i=1390',
   DeviceRegistrar_Administration_TicketAuthorities_RemoveCertificate_InputArguments = 'i=1392',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Size = 'i=1394',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Writable = 'i=1395',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_UserWritable = 'i=1396',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_OpenCount = 'i=1397',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Open_InputArguments = 'i=1402',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Open_OutputArguments = 'i=1403',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Close_InputArguments = 'i=1405',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Read_InputArguments = 'i=1407',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Read_OutputArguments = 'i=1408',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_Write_InputArguments = 'i=1410',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_GetPosition_InputArguments = 'i=1412',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_GetPosition_OutputArguments = 'i=1413',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_SetPosition_InputArguments = 'i=1415',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_LastUpdateTime = 'i=1416',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_OpenWithMasks_InputArguments = 'i=1420',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_OpenWithMasks_OutputArguments = 'i=1421',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_CloseAndUpdate_InputArguments = 'i=1423',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_CloseAndUpdate_OutputArguments = 'i=1424',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_AddCertificate_InputArguments = 'i=1426',
   DeviceRegistrar_Administration_DeviceIdentityAuthorities_RemoveCertificate_InputArguments = 'i=1428',
   OpcUaOnboarding_BinarySchema = 'i=1444',
   OpcUaOnboarding_BinarySchema_NamespaceUri = 'i=1446',
   OpcUaOnboarding_BinarySchema_Deprecated = 'i=1447',
   OpcUaOnboarding_BinarySchema_CertificateAuthorityType = 'i=1448',
   OpcUaOnboarding_BinarySchema_BaseTicketType = 'i=1451',
   OpcUaOnboarding_BinarySchema_DeviceIdentityTicketType = 'i=1454',
   OpcUaOnboarding_BinarySchema_CompositeIdentityTicketType = 'i=1457',
   OpcUaOnboarding_BinarySchema_TicketListType = 'i=1460',
   OpcUaOnboarding_BinarySchema_ManagerDescription = 'i=4208',
   OpcUaOnboarding_XmlSchema = 'i=1468',
   OpcUaOnboarding_XmlSchema_NamespaceUri = 'i=1470',
   OpcUaOnboarding_XmlSchema_Deprecated = 'i=1471',
   OpcUaOnboarding_XmlSchema_CertificateAuthorityType = 'i=1472',
   OpcUaOnboarding_XmlSchema_BaseTicketType = 'i=1475',
   OpcUaOnboarding_XmlSchema_DeviceIdentityTicketType = 'i=1478',
   OpcUaOnboarding_XmlSchema_CompositeIdentityTicketType = 'i=1481',
   OpcUaOnboarding_XmlSchema_TicketListType = 'i=1484',
   OpcUaOnboarding_XmlSchema_ManagerDescription = 'i=4216'
}

export class StatusCode {
   public static isGood(code?: number): boolean {
      return !code || (code & 0xD0000000) === 0;
   }
   public static isUncertain(code?: number): boolean {
      return (code ?? 0 & 0x40000000) !== 0;
   }
   public static isBad(code?: number): boolean {
      return (code ?? 0 & 0x80000000) !== 0;
   }
}