<!--***START***-->
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
  name="UAEndpoints"
  targetNamespace="_EndpointsNamespace_"
  xmlns:tns="_EndpointsNamespace_"
  xmlns:s0="_ServicesNamespace_"
  xmlns:s1="http://localhost.org/UA/SampleServer"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
>
  <wsdl:import namespace="_ServicesNamespace_" location="_ServicesNamespace_" />
  <wsdl:types />

  <wsdl:binding name="UaSoapXmlBinding_ISessionEndpoint" type="s0:ISessionEndpoint">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>

    <wsdl:operation name="InvokeService">
      <soap12:operation soapAction="_Namespace_/InvokeService" style="document"/>
      <wsdl:input name="InvokeServiceMessage">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="InvokeServiceResponseMessage">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvokeServiceFaultMessage">
        <soap12:fault name="InvokeServiceFaultMessage" use="literal" />
      </wsdl:fault>
    </wsdl:operation>

    <!-- Session Binding List -->

  </wsdl:binding>

  <wsdl:binding name="UaSoapXmlBinding_IDiscoveryEndpoint" type="s0:IDiscoveryEndpoint">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>

    <wsdl:operation name="InvokeService">
      <soap12:operation soapAction="_Namespace_/InvokeService" style="document"/>
      <wsdl:input name="InvokeServiceMessage">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="InvokeServiceResponseMessage">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvokeServiceFaultMessage">
        <soap12:fault name="InvokeServiceFaultMessage" use="literal" />
      </wsdl:fault>
    </wsdl:operation>

    <!-- Discovery Binding List -->

  </wsdl:binding>

  <wsdl:binding name="UaSoapXmlBinding_IRegistrationEndpoint" type="s0:IRegistrationEndpoint">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>

    <wsdl:operation name="InvokeService">
      <soap12:operation soapAction="_ServicesNamespace_/InvokeService" style="document"/>
      <wsdl:input name="InvokeServiceMessage">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="InvokeServiceResponseMessage">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvokeServiceFaultMessage">
        <soap12:fault name="InvokeServiceFaultMessage" use="literal" />
      </wsdl:fault>
    </wsdl:operation>

    <!-- Registration Binding List -->

  </wsdl:binding>

  <wsdl:service name="UAService">
    <wsdl:port name="UaSoapXmlBinding_ISessionEndpoint" binding="tns:UaSoapXmlBinding_ISessionEndpoint">
      <soap12:address location="http://localhost/UAService"/>
    </wsdl:port>
    <wsdl:port name="UaSoapXmlBinding_IDiscoveryEndpoint" binding="tns:UaSoapXmlBinding_IDiscoveryEndpoint">
      <soap12:address location="http://localhost/UAService/discovery"/>
    </wsdl:port>
  </wsdl:service>

  <wsdl:service name="UADiscoveryService">
    <wsdl:port name="UaSoapXmlBinding_IDiscoveryEndpoint" binding="tns:UaSoapXmlBinding_IDiscoveryEndpoint">
      <soap12:address location="http://localhost:52601/UADiscovery"/>
    </wsdl:port>
    <wsdl:port name="UaSoapXmlBinding_IRegistrationEndpoint" binding="tns:UaSoapXmlBinding_IRegistrationEndpoint">
      <soap12:address location="http://localhost:52601/UADiscovery/registration"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
<!--***END***-->